name: internship_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  

dependencies:
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  syncfusion_flutter_pdfviewer: ^25.2.4
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
